server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dbName
    password: root
    username: root
    #driver-class-name: com.mysql.cj.jdbc.Driver

  application:
    name: cron-service